package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.Gis;
import com.rytec.rec.db.model.GisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    int countByExample(GisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    int deleteByExample(GisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    int insert(Gis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    int insertSelective(Gis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    List<Gis> selectByExampleWithRowbounds(GisExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    List<Gis> selectByExample(GisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    Gis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") Gis record, @Param("example") GisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    int updateByExample(@Param("record") Gis record, @Param("example") GisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    int updateByPrimaryKeySelective(Gis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gis
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    int updateByPrimaryKey(Gis record);
}