package com.rytec.rec.db.model;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.id
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.name
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.ip
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.port
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.login
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    private String login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.pass
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    private String pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.type
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.other
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.id
     *
     * @return the value of channel.id
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.id
     *
     * @param id the value for channel.id
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.name
     *
     * @return the value of channel.name
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.name
     *
     * @param name the value for channel.name
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.ip
     *
     * @return the value of channel.ip
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.ip
     *
     * @param ip the value for channel.ip
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.port
     *
     * @return the value of channel.port
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.port
     *
     * @param port the value for channel.port
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.login
     *
     * @return the value of channel.login
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.login
     *
     * @param login the value for channel.login
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public void setLogin(String login) {
        this.login = login == null ? null : login.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.pass
     *
     * @return the value of channel.pass
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.pass
     *
     * @param pass the value for channel.pass
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.type
     *
     * @return the value of channel.type
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.type
     *
     * @param type the value for channel.type
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.other
     *
     * @return the value of channel.other
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.other
     *
     * @param other the value for channel.other
     *
     * @mbggenerated Wed Dec 21 21:50:17 CST 2016
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}