package com.rytec.rec.db.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.id
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.cat
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    private Integer cat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.name
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.value
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.id
     *
     * @return the value of config.id
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.id
     *
     * @param id the value for config.id
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.cat
     *
     * @return the value of config.cat
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    public Integer getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.cat
     *
     * @param cat the value for config.cat
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    public void setCat(Integer cat) {
        this.cat = cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.name
     *
     * @return the value of config.name
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.name
     *
     * @param name the value for config.name
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.value
     *
     * @return the value of config.value
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.value
     *
     * @param value the value for config.value
     *
     * @mbggenerated Wed Dec 21 22:03:41 CST 2016
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}