package com.rytec.rec.db.model;

public class Gis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis.id
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis.device
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    private Integer device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis.type
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis.layer
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    private Integer layer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis.data
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gis.style
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    private Integer style;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis.id
     *
     * @return the value of gis.id
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis.id
     *
     * @param id the value for gis.id
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis.device
     *
     * @return the value of gis.device
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public Integer getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis.device
     *
     * @param device the value for gis.device
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public void setDevice(Integer device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis.type
     *
     * @return the value of gis.type
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis.type
     *
     * @param type the value for gis.type
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis.layer
     *
     * @return the value of gis.layer
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis.layer
     *
     * @param layer the value for gis.layer
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis.data
     *
     * @return the value of gis.data
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis.data
     *
     * @param data the value for gis.data
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gis.style
     *
     * @return the value of gis.style
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public Integer getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gis.style
     *
     * @param style the value for gis.style
     *
     * @mbggenerated Tue Jan 03 11:18:35 CST 2017
     */
    public void setStyle(Integer style) {
        this.style = style;
    }
}