package com.rytec.rec.db.model;

import java.util.ArrayList;
import java.util.List;

public class ActionsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public ActionsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRuleIsNull() {
            addCriterion("rule is null");
            return (Criteria) this;
        }

        public Criteria andRuleIsNotNull() {
            addCriterion("rule is not null");
            return (Criteria) this;
        }

        public Criteria andRuleEqualTo(Integer value) {
            addCriterion("rule =", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleNotEqualTo(Integer value) {
            addCriterion("rule <>", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleGreaterThan(Integer value) {
            addCriterion("rule >", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleGreaterThanOrEqualTo(Integer value) {
            addCriterion("rule >=", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleLessThan(Integer value) {
            addCriterion("rule <", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleLessThanOrEqualTo(Integer value) {
            addCriterion("rule <=", value, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleIn(List<Integer> values) {
            addCriterion("rule in", values, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleNotIn(List<Integer> values) {
            addCriterion("rule not in", values, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleBetween(Integer value1, Integer value2) {
            addCriterion("rule between", value1, value2, "rule");
            return (Criteria) this;
        }

        public Criteria andRuleNotBetween(Integer value1, Integer value2) {
            addCriterion("rule not between", value1, value2, "rule");
            return (Criteria) this;
        }

        public Criteria andTargetIsNull() {
            addCriterion("target is null");
            return (Criteria) this;
        }

        public Criteria andTargetIsNotNull() {
            addCriterion("target is not null");
            return (Criteria) this;
        }

        public Criteria andTargetEqualTo(Integer value) {
            addCriterion("target =", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotEqualTo(Integer value) {
            addCriterion("target <>", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetGreaterThan(Integer value) {
            addCriterion("target >", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetGreaterThanOrEqualTo(Integer value) {
            addCriterion("target >=", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetLessThan(Integer value) {
            addCriterion("target <", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetLessThanOrEqualTo(Integer value) {
            addCriterion("target <=", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetIn(List<Integer> values) {
            addCriterion("target in", values, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotIn(List<Integer> values) {
            addCriterion("target not in", values, "target");
            return (Criteria) this;
        }

        public Criteria andTargetBetween(Integer value1, Integer value2) {
            addCriterion("target between", value1, value2, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotBetween(Integer value1, Integer value2) {
            addCriterion("target not between", value1, value2, "target");
            return (Criteria) this;
        }

        public Criteria andActIsNull() {
            addCriterion("act is null");
            return (Criteria) this;
        }

        public Criteria andActIsNotNull() {
            addCriterion("act is not null");
            return (Criteria) this;
        }

        public Criteria andActEqualTo(Integer value) {
            addCriterion("act =", value, "act");
            return (Criteria) this;
        }

        public Criteria andActNotEqualTo(Integer value) {
            addCriterion("act <>", value, "act");
            return (Criteria) this;
        }

        public Criteria andActGreaterThan(Integer value) {
            addCriterion("act >", value, "act");
            return (Criteria) this;
        }

        public Criteria andActGreaterThanOrEqualTo(Integer value) {
            addCriterion("act >=", value, "act");
            return (Criteria) this;
        }

        public Criteria andActLessThan(Integer value) {
            addCriterion("act <", value, "act");
            return (Criteria) this;
        }

        public Criteria andActLessThanOrEqualTo(Integer value) {
            addCriterion("act <=", value, "act");
            return (Criteria) this;
        }

        public Criteria andActIn(List<Integer> values) {
            addCriterion("act in", values, "act");
            return (Criteria) this;
        }

        public Criteria andActNotIn(List<Integer> values) {
            addCriterion("act not in", values, "act");
            return (Criteria) this;
        }

        public Criteria andActBetween(Integer value1, Integer value2) {
            addCriterion("act between", value1, value2, "act");
            return (Criteria) this;
        }

        public Criteria andActNotBetween(Integer value1, Integer value2) {
            addCriterion("act not between", value1, value2, "act");
            return (Criteria) this;
        }

        public Criteria andParmIsNull() {
            addCriterion("parm is null");
            return (Criteria) this;
        }

        public Criteria andParmIsNotNull() {
            addCriterion("parm is not null");
            return (Criteria) this;
        }

        public Criteria andParmEqualTo(String value) {
            addCriterion("parm =", value, "parm");
            return (Criteria) this;
        }

        public Criteria andParmNotEqualTo(String value) {
            addCriterion("parm <>", value, "parm");
            return (Criteria) this;
        }

        public Criteria andParmGreaterThan(String value) {
            addCriterion("parm >", value, "parm");
            return (Criteria) this;
        }

        public Criteria andParmGreaterThanOrEqualTo(String value) {
            addCriterion("parm >=", value, "parm");
            return (Criteria) this;
        }

        public Criteria andParmLessThan(String value) {
            addCriterion("parm <", value, "parm");
            return (Criteria) this;
        }

        public Criteria andParmLessThanOrEqualTo(String value) {
            addCriterion("parm <=", value, "parm");
            return (Criteria) this;
        }

        public Criteria andParmLike(String value) {
            addCriterion("parm like", value, "parm");
            return (Criteria) this;
        }

        public Criteria andParmNotLike(String value) {
            addCriterion("parm not like", value, "parm");
            return (Criteria) this;
        }

        public Criteria andParmIn(List<String> values) {
            addCriterion("parm in", values, "parm");
            return (Criteria) this;
        }

        public Criteria andParmNotIn(List<String> values) {
            addCriterion("parm not in", values, "parm");
            return (Criteria) this;
        }

        public Criteria andParmBetween(String value1, String value2) {
            addCriterion("parm between", value1, value2, "parm");
            return (Criteria) this;
        }

        public Criteria andParmNotBetween(String value1, String value2) {
            addCriterion("parm not between", value1, value2, "parm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table actions
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 14 13:07:30 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}