package com.rytec.rec.db.model;

public class ActionRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actionrule.id
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actionrule.device
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actionrule.sig
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer sig;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actionrule.id
     *
     * @return the value of actionrule.id
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actionrule.id
     *
     * @param id the value for actionrule.id
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actionrule.device
     *
     * @return the value of actionrule.device
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actionrule.device
     *
     * @param device the value for actionrule.device
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setDevice(Integer device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actionrule.sig
     *
     * @return the value of actionrule.sig
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getSig() {
        return sig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actionrule.sig
     *
     * @param sig the value for actionrule.sig
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setSig(Integer sig) {
        this.sig = sig;
    }
}