package com.rytec.rec.db.model;

public class Actions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.id
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.rule
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer rule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.target
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.act
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer act;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actions.parm
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private String parm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.id
     *
     * @return the value of actions.id
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.id
     *
     * @param id the value for actions.id
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.rule
     *
     * @return the value of actions.rule
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.rule
     *
     * @param rule the value for actions.rule
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setRule(Integer rule) {
        this.rule = rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.target
     *
     * @return the value of actions.target
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.target
     *
     * @param target the value for actions.target
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setTarget(Integer target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.act
     *
     * @return the value of actions.act
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getAct() {
        return act;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.act
     *
     * @param act the value for actions.act
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setAct(Integer act) {
        this.act = act;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actions.parm
     *
     * @return the value of actions.parm
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public String getParm() {
        return parm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actions.parm
     *
     * @param parm the value for actions.parm
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setParm(String parm) {
        this.parm = parm == null ? null : parm.trim();
    }
}