package com.rytec.rec.db.model;

public class AlarmVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarmvideo.device
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    private Integer device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarmvideo.sig
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    private Integer sig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alarmvideo.target
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    private Integer target;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarmvideo.device
     *
     * @return the value of alarmvideo.device
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    public Integer getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarmvideo.device
     *
     * @param device the value for alarmvideo.device
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    public void setDevice(Integer device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarmvideo.sig
     *
     * @return the value of alarmvideo.sig
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    public Integer getSig() {
        return sig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarmvideo.sig
     *
     * @param sig the value for alarmvideo.sig
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    public void setSig(Integer sig) {
        this.sig = sig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alarmvideo.target
     *
     * @return the value of alarmvideo.target
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    public Integer getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alarmvideo.target
     *
     * @param target the value for alarmvideo.target
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    public void setTarget(Integer target) {
        this.target = target;
    }
}