package com.rytec.rec.db.model;

public class ChannelNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.id
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.cname
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.ip
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.port
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.login
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private String login;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.pass
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private String pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.ctype
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Integer ctype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.channelConf
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private String channelconf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.nid
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Integer nid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.adr
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Integer adr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.no
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.nname
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private String nname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.ntype
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Integer ntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.nodeConf
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private String nodeconf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.device
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Integer device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.deviceFun
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Integer devicefun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channelnode.enable
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    private Byte enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.id
     *
     * @return the value of channelnode.id
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.id
     *
     * @param id the value for channelnode.id
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.cname
     *
     * @return the value of channelnode.cname
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.cname
     *
     * @param cname the value for channelnode.cname
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.ip
     *
     * @return the value of channelnode.ip
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.ip
     *
     * @param ip the value for channelnode.ip
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.port
     *
     * @return the value of channelnode.port
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.port
     *
     * @param port the value for channelnode.port
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.login
     *
     * @return the value of channelnode.login
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.login
     *
     * @param login the value for channelnode.login
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setLogin(String login) {
        this.login = login == null ? null : login.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.pass
     *
     * @return the value of channelnode.pass
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.pass
     *
     * @param pass the value for channelnode.pass
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.ctype
     *
     * @return the value of channelnode.ctype
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Integer getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.ctype
     *
     * @param ctype the value for channelnode.ctype
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setCtype(Integer ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.channelConf
     *
     * @return the value of channelnode.channelConf
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public String getChannelconf() {
        return channelconf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.channelConf
     *
     * @param channelconf the value for channelnode.channelConf
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setChannelconf(String channelconf) {
        this.channelconf = channelconf == null ? null : channelconf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.nid
     *
     * @return the value of channelnode.nid
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.nid
     *
     * @param nid the value for channelnode.nid
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.adr
     *
     * @return the value of channelnode.adr
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Integer getAdr() {
        return adr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.adr
     *
     * @param adr the value for channelnode.adr
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setAdr(Integer adr) {
        this.adr = adr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.no
     *
     * @return the value of channelnode.no
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.no
     *
     * @param no the value for channelnode.no
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.nname
     *
     * @return the value of channelnode.nname
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public String getNname() {
        return nname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.nname
     *
     * @param nname the value for channelnode.nname
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setNname(String nname) {
        this.nname = nname == null ? null : nname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.ntype
     *
     * @return the value of channelnode.ntype
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Integer getNtype() {
        return ntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.ntype
     *
     * @param ntype the value for channelnode.ntype
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setNtype(Integer ntype) {
        this.ntype = ntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.nodeConf
     *
     * @return the value of channelnode.nodeConf
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public String getNodeconf() {
        return nodeconf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.nodeConf
     *
     * @param nodeconf the value for channelnode.nodeConf
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setNodeconf(String nodeconf) {
        this.nodeconf = nodeconf == null ? null : nodeconf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.device
     *
     * @return the value of channelnode.device
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Integer getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.device
     *
     * @param device the value for channelnode.device
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setDevice(Integer device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.deviceFun
     *
     * @return the value of channelnode.deviceFun
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Integer getDevicefun() {
        return devicefun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.deviceFun
     *
     * @param devicefun the value for channelnode.deviceFun
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setDevicefun(Integer devicefun) {
        this.devicefun = devicefun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channelnode.enable
     *
     * @return the value of channelnode.enable
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channelnode.enable
     *
     * @param enable the value for channelnode.enable
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }
}