package com.rytec.rec.db.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.id
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.cat
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    private Integer cat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.name
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.value
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.type
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.fun
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    private Integer fun;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.id
     *
     * @return the value of config.id
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.id
     *
     * @param id the value for config.id
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.cat
     *
     * @return the value of config.cat
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public Integer getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.cat
     *
     * @param cat the value for config.cat
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public void setCat(Integer cat) {
        this.cat = cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.name
     *
     * @return the value of config.name
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.name
     *
     * @param name the value for config.name
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.value
     *
     * @return the value of config.value
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.value
     *
     * @param value the value for config.value
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.type
     *
     * @return the value of config.type
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.type
     *
     * @param type the value for config.type
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.fun
     *
     * @return the value of config.fun
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public Integer getFun() {
        return fun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.fun
     *
     * @param fun the value for config.fun
     *
     * @mbggenerated Thu Dec 21 15:02:22 CST 2017
     */
    public void setFun(Integer fun) {
        this.fun = fun;
    }
}