package com.rytec.rec.db.model;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.id
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.no
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.name
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.type
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.icon
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    private Integer icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.opt
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    private String opt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.no
     *
     * @return the value of device.no
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.no
     *
     * @param no the value for device.no
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.name
     *
     * @return the value of device.name
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.name
     *
     * @param name the value for device.name
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.type
     *
     * @return the value of device.type
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.type
     *
     * @param type the value for device.type
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.icon
     *
     * @return the value of device.icon
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public Integer getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.icon
     *
     * @param icon the value for device.icon
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public void setIcon(Integer icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.opt
     *
     * @return the value of device.opt
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public String getOpt() {
        return opt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.opt
     *
     * @param opt the value for device.opt
     *
     * @mbggenerated Wed Apr 11 16:32:32 CST 2018
     */
    public void setOpt(String opt) {
        this.opt = opt == null ? null : opt.trim();
    }
}