package com.rytec.rec.db.model;

public class DeviceNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.id
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.dno
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Integer dno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.dname
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.dtype
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Integer dtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.iec61850
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Byte iec61850;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.nid
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Integer nid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.cid
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.nadd
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Integer nadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.nno
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Integer nno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.ntype
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Integer ntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.conf
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private String conf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicenode.nfun
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    private Integer nfun;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.id
     *
     * @return the value of devicenode.id
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.id
     *
     * @param id the value for devicenode.id
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.dno
     *
     * @return the value of devicenode.dno
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Integer getDno() {
        return dno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.dno
     *
     * @param dno the value for devicenode.dno
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setDno(Integer dno) {
        this.dno = dno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.dname
     *
     * @return the value of devicenode.dname
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.dname
     *
     * @param dname the value for devicenode.dname
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.dtype
     *
     * @return the value of devicenode.dtype
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Integer getDtype() {
        return dtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.dtype
     *
     * @param dtype the value for devicenode.dtype
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setDtype(Integer dtype) {
        this.dtype = dtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.iec61850
     *
     * @return the value of devicenode.iec61850
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Byte getIec61850() {
        return iec61850;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.iec61850
     *
     * @param iec61850 the value for devicenode.iec61850
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setIec61850(Byte iec61850) {
        this.iec61850 = iec61850;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.nid
     *
     * @return the value of devicenode.nid
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.nid
     *
     * @param nid the value for devicenode.nid
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.cid
     *
     * @return the value of devicenode.cid
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.cid
     *
     * @param cid the value for devicenode.cid
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.nadd
     *
     * @return the value of devicenode.nadd
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Integer getNadd() {
        return nadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.nadd
     *
     * @param nadd the value for devicenode.nadd
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setNadd(Integer nadd) {
        this.nadd = nadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.nno
     *
     * @return the value of devicenode.nno
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Integer getNno() {
        return nno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.nno
     *
     * @param nno the value for devicenode.nno
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setNno(Integer nno) {
        this.nno = nno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.ntype
     *
     * @return the value of devicenode.ntype
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Integer getNtype() {
        return ntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.ntype
     *
     * @param ntype the value for devicenode.ntype
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setNtype(Integer ntype) {
        this.ntype = ntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.conf
     *
     * @return the value of devicenode.conf
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public String getConf() {
        return conf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.conf
     *
     * @param conf the value for devicenode.conf
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setConf(String conf) {
        this.conf = conf == null ? null : conf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicenode.nfun
     *
     * @return the value of devicenode.nfun
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public Integer getNfun() {
        return nfun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicenode.nfun
     *
     * @param nfun the value for devicenode.nfun
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    public void setNfun(Integer nfun) {
        this.nfun = nfun;
    }
}