package com.rytec.rec.db.model;

public class DeviceGis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegis.did
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegis.dno
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    private Integer dno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegis.dname
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    private String dname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegis.dtype
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    private Integer dtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegis.icon
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    private Integer icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegis.gid
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegis.gtype
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    private Integer gtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegis.layer
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    private Integer layer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicegis.data
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegis.did
     *
     * @return the value of devicegis.did
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegis.did
     *
     * @param did the value for devicegis.did
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegis.dno
     *
     * @return the value of devicegis.dno
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public Integer getDno() {
        return dno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegis.dno
     *
     * @param dno the value for devicegis.dno
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public void setDno(Integer dno) {
        this.dno = dno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegis.dname
     *
     * @return the value of devicegis.dname
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegis.dname
     *
     * @param dname the value for devicegis.dname
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegis.dtype
     *
     * @return the value of devicegis.dtype
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public Integer getDtype() {
        return dtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegis.dtype
     *
     * @param dtype the value for devicegis.dtype
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public void setDtype(Integer dtype) {
        this.dtype = dtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegis.icon
     *
     * @return the value of devicegis.icon
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public Integer getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegis.icon
     *
     * @param icon the value for devicegis.icon
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public void setIcon(Integer icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegis.gid
     *
     * @return the value of devicegis.gid
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegis.gid
     *
     * @param gid the value for devicegis.gid
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegis.gtype
     *
     * @return the value of devicegis.gtype
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public Integer getGtype() {
        return gtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegis.gtype
     *
     * @param gtype the value for devicegis.gtype
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public void setGtype(Integer gtype) {
        this.gtype = gtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegis.layer
     *
     * @return the value of devicegis.layer
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegis.layer
     *
     * @param layer the value for devicegis.layer
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicegis.data
     *
     * @return the value of devicegis.data
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicegis.data
     *
     * @param data the value for devicegis.data
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}