package com.rytec.rec.db.model;

public class Device {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.id
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.no
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.name
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.type
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.icon
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    private Integer icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.lnodetype
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    private String lnodetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.lnodenum
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    private Integer lnodenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.opt
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    private String opt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.no
     *
     * @return the value of device.no
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.no
     *
     * @param no the value for device.no
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.name
     *
     * @return the value of device.name
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.name
     *
     * @param name the value for device.name
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.type
     *
     * @return the value of device.type
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.type
     *
     * @param type the value for device.type
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.icon
     *
     * @return the value of device.icon
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public Integer getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.icon
     *
     * @param icon the value for device.icon
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public void setIcon(Integer icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.lnodetype
     *
     * @return the value of device.lnodetype
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public String getLnodetype() {
        return lnodetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.lnodetype
     *
     * @param lnodetype the value for device.lnodetype
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public void setLnodetype(String lnodetype) {
        this.lnodetype = lnodetype == null ? null : lnodetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.lnodenum
     *
     * @return the value of device.lnodenum
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public Integer getLnodenum() {
        return lnodenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.lnodenum
     *
     * @param lnodenum the value for device.lnodenum
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public void setLnodenum(Integer lnodenum) {
        this.lnodenum = lnodenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.opt
     *
     * @return the value of device.opt
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public String getOpt() {
        return opt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.opt
     *
     * @param opt the value for device.opt
     *
     * @mbggenerated Fri Feb 24 07:17:56 CST 2017
     */
    public void setOpt(String opt) {
        this.opt = opt == null ? null : opt.trim();
    }
}