package com.rytec.rec.db.model;

public class GisLayer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gislayer.id
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gislayer.name
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gislayer.file
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gislayer.zoom
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    private Integer zoom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gislayer.id
     *
     * @return the value of gislayer.id
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gislayer.id
     *
     * @param id the value for gislayer.id
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gislayer.name
     *
     * @return the value of gislayer.name
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gislayer.name
     *
     * @param name the value for gislayer.name
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gislayer.file
     *
     * @return the value of gislayer.file
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gislayer.file
     *
     * @param file the value for gislayer.file
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gislayer.zoom
     *
     * @return the value of gislayer.zoom
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    public Integer getZoom() {
        return zoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gislayer.zoom
     *
     * @param zoom the value for gislayer.zoom
     *
     * @mbg.generated Tue Jun 12 22:29:09 CST 2018
     */
    public void setZoom(Integer zoom) {
        this.zoom = zoom;
    }
}