package com.rytec.rec.db.model;

public class Node {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.id
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.cid
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.adr
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    private Integer adr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.no
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.name
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.type
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.opt
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    private String opt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.device
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    private Integer device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node.deviceFun
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    private Integer devicefun;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.id
     *
     * @return the value of node.id
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.id
     *
     * @param id the value for node.id
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.cid
     *
     * @return the value of node.cid
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.cid
     *
     * @param cid the value for node.cid
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.adr
     *
     * @return the value of node.adr
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public Integer getAdr() {
        return adr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.adr
     *
     * @param adr the value for node.adr
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public void setAdr(Integer adr) {
        this.adr = adr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.no
     *
     * @return the value of node.no
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.no
     *
     * @param no the value for node.no
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.name
     *
     * @return the value of node.name
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.name
     *
     * @param name the value for node.name
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.type
     *
     * @return the value of node.type
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.type
     *
     * @param type the value for node.type
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.opt
     *
     * @return the value of node.opt
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public String getOpt() {
        return opt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.opt
     *
     * @param opt the value for node.opt
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public void setOpt(String opt) {
        this.opt = opt == null ? null : opt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.device
     *
     * @return the value of node.device
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public Integer getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.device
     *
     * @param device the value for node.device
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public void setDevice(Integer device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node.deviceFun
     *
     * @return the value of node.deviceFun
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public Integer getDevicefun() {
        return devicefun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node.deviceFun
     *
     * @param devicefun the value for node.deviceFun
     *
     * @mbggenerated Sat Jan 21 12:14:57 CST 2017
     */
    public void setDevicefun(Integer devicefun) {
        this.devicefun = devicefun;
    }
}