package com.rytec.rec.db.model;

public class NodeRedirect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noderedirect.id
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noderedirect.node
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    private Integer node;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noderedirect.device
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    private Integer device;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column noderedirect.devicefun
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    private Integer devicefun;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noderedirect.id
     *
     * @return the value of noderedirect.id
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noderedirect.id
     *
     * @param id the value for noderedirect.id
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noderedirect.node
     *
     * @return the value of noderedirect.node
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    public Integer getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noderedirect.node
     *
     * @param node the value for noderedirect.node
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    public void setNode(Integer node) {
        this.node = node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noderedirect.device
     *
     * @return the value of noderedirect.device
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    public Integer getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noderedirect.device
     *
     * @param device the value for noderedirect.device
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    public void setDevice(Integer device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column noderedirect.devicefun
     *
     * @return the value of noderedirect.devicefun
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    public Integer getDevicefun() {
        return devicefun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column noderedirect.devicefun
     *
     * @param devicefun the value for noderedirect.devicefun
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    public void setDevicefun(Integer devicefun) {
        this.devicefun = devicefun;
    }
}