package com.rytec.rec.db.model;

public class PanoramaDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panoramadevice.id
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panoramadevice.device
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    private Integer device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panoramadevice.scene
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    private Integer scene;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panoramadevice.pitch
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    private Float pitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panoramadevice.yaw
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    private Float yaw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panoramadevice.id
     *
     * @return the value of panoramadevice.id
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panoramadevice.id
     *
     * @param id the value for panoramadevice.id
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panoramadevice.device
     *
     * @return the value of panoramadevice.device
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public Integer getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panoramadevice.device
     *
     * @param device the value for panoramadevice.device
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public void setDevice(Integer device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panoramadevice.scene
     *
     * @return the value of panoramadevice.scene
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public Integer getScene() {
        return scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panoramadevice.scene
     *
     * @param scene the value for panoramadevice.scene
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public void setScene(Integer scene) {
        this.scene = scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panoramadevice.pitch
     *
     * @return the value of panoramadevice.pitch
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public Float getPitch() {
        return pitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panoramadevice.pitch
     *
     * @param pitch the value for panoramadevice.pitch
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public void setPitch(Float pitch) {
        this.pitch = pitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panoramadevice.yaw
     *
     * @return the value of panoramadevice.yaw
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public Float getYaw() {
        return yaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panoramadevice.yaw
     *
     * @param yaw the value for panoramadevice.yaw
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public void setYaw(Float yaw) {
        this.yaw = yaw;
    }
}