package com.rytec.rec.db.model;

public class Panorama {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panorama.id
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panorama.name
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column panorama.file
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    private String file;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panorama.id
     *
     * @return the value of panorama.id
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panorama.id
     *
     * @param id the value for panorama.id
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panorama.name
     *
     * @return the value of panorama.name
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panorama.name
     *
     * @param name the value for panorama.name
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column panorama.file
     *
     * @return the value of panorama.file
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column panorama.file
     *
     * @param file the value for panorama.file
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }
}