package com.rytec.rec.db.model;

public class RuleAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruleaction.rid
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruleaction.device
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruleaction.sig
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer sig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruleaction.aid
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruleaction.target
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruleaction.act
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private Integer act;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ruleaction.parm
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    private String parm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruleaction.rid
     *
     * @return the value of ruleaction.rid
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruleaction.rid
     *
     * @param rid the value for ruleaction.rid
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruleaction.device
     *
     * @return the value of ruleaction.device
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruleaction.device
     *
     * @param device the value for ruleaction.device
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setDevice(Integer device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruleaction.sig
     *
     * @return the value of ruleaction.sig
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getSig() {
        return sig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruleaction.sig
     *
     * @param sig the value for ruleaction.sig
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setSig(Integer sig) {
        this.sig = sig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruleaction.aid
     *
     * @return the value of ruleaction.aid
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruleaction.aid
     *
     * @param aid the value for ruleaction.aid
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruleaction.target
     *
     * @return the value of ruleaction.target
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruleaction.target
     *
     * @param target the value for ruleaction.target
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setTarget(Integer target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruleaction.act
     *
     * @return the value of ruleaction.act
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public Integer getAct() {
        return act;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruleaction.act
     *
     * @param act the value for ruleaction.act
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setAct(Integer act) {
        this.act = act;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ruleaction.parm
     *
     * @return the value of ruleaction.parm
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public String getParm() {
        return parm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ruleaction.parm
     *
     * @param parm the value for ruleaction.parm
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    public void setParm(String parm) {
        this.parm = parm == null ? null : parm.trim();
    }
}