package com.rytec.rec.channel.KhFiber.db.mapper;

import com.rytec.rec.channel.KhFiber.db.model.KhDataAlarm;
import com.rytec.rec.channel.KhFiber.db.model.KhDataAlarmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KhDataAlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DataAlarm
     *
     * @mbg.generated Thu Apr 19 18:56:21 CST 2018
     */
    long countByExample(KhDataAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DataAlarm
     *
     * @mbg.generated Thu Apr 19 18:56:21 CST 2018
     */
    int deleteByExample(KhDataAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DataAlarm
     *
     * @mbg.generated Thu Apr 19 18:56:21 CST 2018
     */
    int insert(KhDataAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DataAlarm
     *
     * @mbg.generated Thu Apr 19 18:56:21 CST 2018
     */
    int insertSelective(KhDataAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DataAlarm
     *
     * @mbg.generated Thu Apr 19 18:56:21 CST 2018
     */
    List<KhDataAlarm> selectByExampleWithRowbounds(KhDataAlarmExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DataAlarm
     *
     * @mbg.generated Thu Apr 19 18:56:21 CST 2018
     */
    List<KhDataAlarm> selectByExample(KhDataAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DataAlarm
     *
     * @mbg.generated Thu Apr 19 18:56:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") KhDataAlarm record, @Param("example") KhDataAlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DataAlarm
     *
     * @mbg.generated Thu Apr 19 18:56:21 CST 2018
     */
    int updateByExample(@Param("record") KhDataAlarm record, @Param("example") KhDataAlarmExample example);
}