package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.Actions;
import com.rytec.rec.db.model.ActionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ActionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int countByExample(ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int deleteByExample(ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int insert(Actions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int insertSelective(Actions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    List<Actions> selectByExampleWithRowbounds(ActionsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    List<Actions> selectByExample(ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    Actions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") Actions record, @Param("example") ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int updateByExample(@Param("record") Actions record, @Param("example") ActionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int updateByPrimaryKeySelective(Actions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actions
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int updateByPrimaryKey(Actions record);
}