package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.Alarm;
import com.rytec.rec.db.model.AlarmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AlarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    int countByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    int deleteByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    int insert(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    int insertSelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    List<Alarm> selectByExampleWithRowbounds(AlarmExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    List<Alarm> selectByExample(AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    Alarm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    int updateByExample(@Param("record") Alarm record, @Param("example") AlarmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    int updateByPrimaryKeySelective(Alarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbggenerated Thu Apr 20 09:12:15 CST 2017
     */
    int updateByPrimaryKey(Alarm record);
}