package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.AlarmVideo;
import com.rytec.rec.db.model.AlarmVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AlarmVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmvideo
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    int countByExample(AlarmVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmvideo
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    int deleteByExample(AlarmVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmvideo
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    int insert(AlarmVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmvideo
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    int insertSelective(AlarmVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmvideo
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    List<AlarmVideo> selectByExampleWithRowbounds(AlarmVideoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmvideo
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    List<AlarmVideo> selectByExample(AlarmVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmvideo
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") AlarmVideo record, @Param("example") AlarmVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarmvideo
     *
     * @mbggenerated Thu Apr 20 16:54:58 CST 2017
     */
    int updateByExample(@Param("record") AlarmVideo record, @Param("example") AlarmVideoExample example);
}