package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.ChannelNode;
import com.rytec.rec.db.model.ChannelNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ChannelNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channelnode
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    int countByExample(ChannelNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channelnode
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    int deleteByExample(ChannelNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channelnode
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    int insert(ChannelNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channelnode
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    int insertSelective(ChannelNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channelnode
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    List<ChannelNode> selectByExampleWithRowbounds(ChannelNodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channelnode
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    List<ChannelNode> selectByExample(ChannelNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channelnode
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") ChannelNode record, @Param("example") ChannelNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channelnode
     *
     * @mbggenerated Mon Apr 09 11:20:55 CST 2018
     */
    int updateByExample(@Param("record") ChannelNode record, @Param("example") ChannelNodeExample example);
}