package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.DeviceGis;
import com.rytec.rec.db.model.DeviceGisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DeviceGisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicegis
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    int countByExample(DeviceGisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicegis
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    int deleteByExample(DeviceGisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicegis
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    int insert(DeviceGis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicegis
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    int insertSelective(DeviceGis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicegis
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    List<DeviceGis> selectByExampleWithRowbounds(DeviceGisExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicegis
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    List<DeviceGis> selectByExample(DeviceGisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicegis
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") DeviceGis record, @Param("example") DeviceGisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicegis
     *
     * @mbggenerated Mon Apr 09 21:02:09 CST 2018
     */
    int updateByExample(@Param("record") DeviceGis record, @Param("example") DeviceGisExample example);
}