package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.DeviceNode;
import com.rytec.rec.db.model.DeviceNodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DeviceNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicenode
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    int countByExample(DeviceNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicenode
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    int deleteByExample(DeviceNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicenode
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    int insert(DeviceNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicenode
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    int insertSelective(DeviceNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicenode
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    List<DeviceNode> selectByExampleWithRowbounds(DeviceNodeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicenode
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    List<DeviceNode> selectByExample(DeviceNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicenode
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") DeviceNode record, @Param("example") DeviceNodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicenode
     *
     * @mbggenerated Sat Jun 17 10:59:06 CST 2017
     */
    int updateByExample(@Param("record") DeviceNode record, @Param("example") DeviceNodeExample example);
}