package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.NodeRedirect;
import com.rytec.rec.db.model.NodeRedirectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NodeRedirectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    long countByExample(NodeRedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    int deleteByExample(NodeRedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    int insert(NodeRedirect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    int insertSelective(NodeRedirect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    List<NodeRedirect> selectByExampleWithRowbounds(NodeRedirectExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    List<NodeRedirect> selectByExample(NodeRedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    NodeRedirect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") NodeRedirect record, @Param("example") NodeRedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    int updateByExample(@Param("record") NodeRedirect record, @Param("example") NodeRedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    int updateByPrimaryKeySelective(NodeRedirect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table noderedirect
     *
     * @mbg.generated Wed Jun 20 16:00:51 CST 2018
     */
    int updateByPrimaryKey(NodeRedirect record);
}