package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.Panorama;
import com.rytec.rec.db.model.PanoramaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PanoramaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    int countByExample(PanoramaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    int deleteByExample(PanoramaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    int insert(Panorama record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    int insertSelective(Panorama record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    List<Panorama> selectByExampleWithRowbounds(PanoramaExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    List<Panorama> selectByExample(PanoramaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    Panorama selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") Panorama record, @Param("example") PanoramaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    int updateByExample(@Param("record") Panorama record, @Param("example") PanoramaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    int updateByPrimaryKeySelective(Panorama record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table panorama
     *
     * @mbggenerated Wed May 10 09:18:04 CST 2017
     */
    int updateByPrimaryKey(Panorama record);
}