package com.rytec.rec.db.mapper;

import com.rytec.rec.db.model.RuleAction;
import com.rytec.rec.db.model.RuleActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RuleActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruleaction
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int countByExample(RuleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruleaction
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int deleteByExample(RuleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruleaction
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int insert(RuleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruleaction
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int insertSelective(RuleAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruleaction
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    List<RuleAction> selectByExampleWithRowbounds(RuleActionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruleaction
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    List<RuleAction> selectByExample(RuleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruleaction
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") RuleAction record, @Param("example") RuleActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ruleaction
     *
     * @mbggenerated Tue Feb 14 13:07:30 CST 2017
     */
    int updateByExample(@Param("record") RuleAction record, @Param("example") RuleActionExample example);
}